package org.softserve.academy;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
//import org.junit.Test;
//import static org.junit.Assert.*;

import static org.junit.jupiter.api.Assertions.*;

class Task1Test {

    @BeforeEach
    void setUp() {
    }

    @AfterEach
    void tearDown() {
    }

    @Test
    void getTotal() {
    }

    @Test
    void getAverage() {
    }
    // Generated by CodiumAI
    @Test
    public void test_getTotal_twoPositiveNumbers() {
        double number1 = 5.0;
        double number2 = 7.0;
        double expectedTotal = 12.0;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

    // Can get the total of two negative numbers
    @Test
    public void test_getTotal_twoNegativeNumbers() {
        double number1 = -5.0;
        double number2 = -7.0;
        double expectedTotal = -12.0;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

    // Can get the total of a positive and a negative number
    @Test
    public void test_getTotal_positiveAndNegativeNumber() {
        double number1 = 5.0;
        double number2 = -7.0;
        double expectedTotal = -2.0;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

    // Can get the total of 0 and a positive number
    @Test
    public void test_getTotal_zeroAndPositiveNumber() {
        double number1 = 0.0;
        double number2 = 7.0;
        double expectedTotal = 7.0;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

    // Can get the total of 0 and a negative number
    @Test
    public void test_getTotal_zeroAndNegativeNumber() {
        double number1 = 0.0;
        double number2 = -7.0;
        double expectedTotal = -7.0;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

    // Can get the total of 0 and a decimal number
    @Test
    public void test_getTotal_zeroAndDecimalNumber() {
        double number1 = 0.0;
        double number2 = 3.5;
        double expectedTotal = 3.5;

        double actualTotal = Task1.getTotal(number1, number2);

        assertEquals(expectedTotal, actualTotal, 0.01);
    }

}


